name: rrh
description: "Rwanda Resilience Hub"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_auth: ^5.5.4
  firebase_database: ^11.3.6
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.6
  firebase_storage: ^12.4.6
  cloud_firestore: 5.6.9
  json_annotation: ^4.7.0
  flutter_local_notifications: ^19.2.1
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  intl: ^0.18.0
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^3.0.0
  injectable: ^2.3.2
  get_it: ^8.0.3
  flutter_secure_storage: ^10.0.0-beta.4
  connectivity_plus: ^6.1.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.1
  image_picker: ^1.0.5
  url_launcher: ^6.2.2
  weather: ^3.1.1
  geocoding: ^4.0.0
  weather_icons: ^3.0.0
  go_router: ^15.1.2
  logging: ^1.2.0
  file_picker: ^10.1.9
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.4.1
  freezed: ^3.0.6
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env